server:
  port: 8082
spring:
  application:
    name: rookie-mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'