server:
  port: 8201
spring:
  application:
    name: mall-gateway
  #  profiles:
  #    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'