server:
  port: 8082
spring:
  application:
    name: rookie-mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: true
    tags:
        application: ${spring.application.name}
    web:
      server:
        auto-time-requests: true
    endpoints:
      prometheus:
        id: springmetrics
      web:
        exposure:
          include: health,info,env,prometheus,metrics,httptrace,threaddump,heapdump,springmetrics